verbosity: 5
enable_cache_lookup: true
toplist_fname: testdomains.txt
subnets_fname: subshort.txt
no_of_domains: 10 # set to -1 to disable 
simul_ecs_reqs: 100
simul_ns_reqs: 1
routine_stop_timeout: 10
nameserver_writeout: true
intermediate_depth: 2
